"""
main.py — Application entry point.

Responsibilities:
  1. Mount the FastMCP server at /mcp  (primary MCP interface)
  2. Auto-register MCP tools as documented REST routes via docs_generator
  3. Serve Swagger UI at /docs (auto-generated, always in sync with MCP tools)
  4. Serve private key file downloads at /terraform/keys/{id}/{filename}

All business logic lives in mcp_server.py and the services/ layer.
This file contains zero business logic.
"""

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response

load_dotenv()

from mcp_server import mcp
from docs_generator import register_mcp_docs_routes
from services.execution_service import get_key_file

_mcp_http_app = mcp.http_app(path="/")

app = FastAPI(
    title="Agentic Cloud Assistant — MCP API",
    description=(
        "AI-powered AWS management tool. "
        "Primary interface: POST /mcp (MCP protocol). "
        "These /tools/* endpoints are auto-generated from MCP tool schemas "
        "for testing and documentation purposes."
    ),
    version="2.0.0",
    lifespan=_mcp_http_app.lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],
    allow_methods=["GET", "POST", "DELETE"],
    allow_headers=["*"],
    expose_headers=["mcp-session-id"],
)

# Mount MCP server — handles all /mcp requests
app.mount("/mcp", _mcp_http_app)

# Auto-generate Swagger-documented REST test routes from MCP tool schemas.
# Every @mcp.tool() in mcp_server.py gets a POST /tools/{name} endpoint here.
register_mcp_docs_routes(app, mcp)


@app.get("/health", tags=["Health"], summary="Server uptime check")
def health():
    return {"status": "ok", "version": "2.0.0", "mcp_endpoint": "POST /mcp"}


@app.get(
    "/terraform/keys/{execution_id}/{filename}",
    tags=["Terraform"],
    summary="Download a .pem private key generated by a Terraform apply",
)
def download_key_file(execution_id: str, filename: str):
    """
    Binary file download — cannot be an MCP tool because MCP returns JSON only.
    This is the one endpoint that must remain as a real REST route.
    """
    try:
        key_bytes = get_key_file(execution_id, filename)
        return Response(
            content=key_bytes,
            media_type="application/x-pem-file",
            headers={
                "Content-Disposition": f'attachment; filename="{filename}"',
                "X-Content-Type-Options": "nosniff",
            },
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except FileNotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))


if __name__ == "__main__":
    import uvicorn

    print("ACA backend starting on http://localhost:8000")
    print("  MCP endpoint : POST http://localhost:8000/mcp")
    print("  Swagger docs : http://localhost:8000/docs")
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
