"""
main.py — Application entry point.

Responsibilities:
  1. Mount the FastMCP server at /mcp  (primary MCP interface)
  2. Auto-register MCP tools as documented REST routes via docs_generator
  3. Serve Swagger UI at /docs (auto-generated, always in sync with MCP tools)
  4. Serve private key file downloads at /terraform/keys/{id}/{filename}

All business logic lives in mcp_server.py and the services/ layer.
This file contains zero business logic.
"""

from dotenv import load_dotenv
from fastapi import FastAPI, File, Form, HTTPException, Query, Request, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response, StreamingResponse

load_dotenv()

from mcp_server import mcp
from docs_generator import register_mcp_docs_routes
from services.execution_service import get_key_file

_mcp_http_app = mcp.http_app(path="/")

app = FastAPI(
    title="Agentic Cloud Assistant — MCP API",
    description=(
        "AI-powered AWS management tool. "
        "Primary interface: POST /mcp (MCP protocol). "
        "These /tools/* endpoints are auto-generated from MCP tool schemas "
        "for testing and documentation purposes."
    ),
    version="2.0.0",
    lifespan=_mcp_http_app.lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],
    allow_methods=["GET", "POST", "DELETE"],
    allow_headers=["*"],
    expose_headers=["mcp-session-id"],
)

# Mount MCP server — handles all /mcp requests
app.mount("/mcp", _mcp_http_app)

# Auto-generate Swagger-documented REST test routes from MCP tool schemas.
# Every @mcp.tool() in mcp_server.py gets a POST /tools/{name} endpoint here.
register_mcp_docs_routes(app, mcp)


@app.get("/health", tags=["Health"], summary="Server uptime check")
def health():
    return {"status": "ok", "version": "2.0.0", "mcp_endpoint": "POST /mcp"}


@app.get(
    "/terraform/keys/{execution_id}/{filename}",
    tags=["Terraform"],
    summary="Download a .pem private key generated by a Terraform apply",
)
def download_key_file(execution_id: str, filename: str):
    """
    Binary file download — cannot be an MCP tool because MCP returns JSON only.
    This is the one endpoint that must remain as a real REST route.
    """
    try:
        key_bytes = get_key_file(execution_id, filename)
        return Response(
            content=key_bytes,
            media_type="application/x-pem-file",
            headers={
                "Content-Disposition": f'attachment; filename="{filename}"',
                "X-Content-Type-Options": "nosniff",
            },
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except FileNotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))


try:
    from rag.knowledge_base import knowledge_base as _knowledge_base
    _RAG_AVAILABLE = True
except Exception:
    _RAG_AVAILABLE = False


@app.post(
    "/rag/documents/upload",
    tags=["Knowledge Base"],
    summary="Upload a PDF or plain-text file to the ChromaDB knowledge base",
)
async def upload_rag_document(
    file: UploadFile = File(...),
    doc_id: str = Form(...),
    resource_type: str = Form("general"),
):
    """
    Multipart file upload — cannot be an MCP tool parameter because MCP is JSON-only.
    This mirrors the rag_upload_file MCP tool but accepts raw bytes via multipart/form-data.
    """
    if not _RAG_AVAILABLE:
        raise HTTPException(status_code=503, detail="RAG knowledge base is not available.")
    try:
        content = await file.read()
        if file.filename and file.filename.lower().endswith(".pdf"):
            import io
            import PyPDF2
            pdf_reader = PyPDF2.PdfReader(io.BytesIO(content))
            text = "\n\n".join(p.extract_text() or "" for p in pdf_reader.pages).strip()
        else:
            text = content.decode("utf-8", errors="ignore").strip()
        if not text:
            raise HTTPException(status_code=422, detail="No text could be extracted from the file.")
        result = _knowledge_base.add_document(
            doc_id=doc_id,
            text=text,
            metadata={"resource_type": resource_type, "filename": file.filename or ""},
        )
        return {"chunks_added": result.get("chunks_added", 0), "doc_id": doc_id}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


from usage_log import usage_summary as _usage_summary
from services.ollama_service import probe_ollama, stream_ollama_pull
from ollama_recommender import RecommendContext, llm_explanation, recommend
from ollama_catalog import CLOUD_MODELS
from mcp_server import _PULL_CATALOG_IDS

@app.get("/api/usage/summary", tags=["Usage"])
async def api_usage_summary(window_hours: int = Query(24)):
    return _usage_summary(window_hours=window_hours)


@app.get("/api/ollama/status", tags=["Ollama"])
async def api_ollama_status(base_url: str = Query("http://localhost:11434")):
    return await probe_ollama(base_url)


@app.post("/api/ollama/pull", tags=["Ollama"])
async def api_ollama_pull(request: Request):
    body = await request.json()
    model = body.get("model", "")
    base_url = body.get("base_url", "http://localhost:11434")
    if model not in _PULL_CATALOG_IDS:
        raise HTTPException(status_code=400, detail="model_not_in_catalog")
    return StreamingResponse(stream_ollama_pull(base_url, model), media_type="application/x-ndjson")


@app.post("/api/ollama/recommend", tags=["Ollama"])
async def api_ollama_recommend(request: Request):
    import asyncio
    body = await request.json()
    primary_use    = body.get("primary_use", "chat")
    latency_pref   = body.get("latency_pref", "balanced")
    scan_size      = body.get("current_scan_size_bucket", "none")
    anthropic_key  = body.get("anthropic_key") or None
    groq_key       = body.get("groq_key") or None

    summary = _usage_summary()
    context = RecommendContext(
        primary_use=primary_use,
        latency_pref=latency_pref,
        scan_size_bucket=scan_size,
        dominant_recent_action=summary.get("dominant_action"),
        history_event_count=summary.get("total_events", 0),
    )
    catalog_ids = [m["id"] for m in CLOUD_MODELS]
    ranked = recommend(context, catalog_ids)

    explanations = await asyncio.gather(
        *[llm_explanation(r, context, anthropic_key, groq_key) for r in ranked],
        return_exceptions=True,
    )

    recs_out = []
    for rec, expl in zip(ranked, explanations):
        if isinstance(expl, Exception):
            expl = rec.template_explanation
            expl_source = "template"
        else:
            expl_source = "llm" if (anthropic_key or groq_key) else "template"
        top_features = sorted(rec.feature_breakdown, key=rec.feature_breakdown.__getitem__, reverse=True)[:2]
        recs_out.append({
            "model_id": rec.model_id, "rank": rec.rank, "score": rec.score,
            "explanation": expl, "explanation_source": expl_source,
            "feature_breakdown": rec.feature_breakdown, "top_features": top_features,
        })

    return {
        "recommendations": recs_out,
        "context_used": {
            "primary_use": primary_use, "scan_size_bucket": scan_size,
            "dominant_recent_action": summary.get("dominant_action"),
            "history_event_count": summary.get("total_events", 0),
        },
    }


if __name__ == "__main__":
    import uvicorn

    print("ACA backend starting on http://localhost:8000")
    print("  MCP endpoint : POST http://localhost:8000/mcp")
    print("  Swagger docs : http://localhost:8000/docs")
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
